### ISSUE TITLE
Mini Roadmap

### ISSUE THREAD

**Issue by GarciaFreelancer** [GarciaFreelancer/sos-api#1]
- [ ] **Configurações iniciais**
  - [x] Nome do projecto
  - [ ] Locale
  - [x] Timezone
  - [ ] Descrever o projecto no ficheio Readme
- [x] **Acessibildade**
  - [x] Autenticação com Token
    - [x] Instalar e configuarar biblioteca JWTAuth - Json Web Token Authentication
    - [x] Criar conta
    - [x] Confirmação de conta por e-mail
    - [x] Login
    - [x] Logout
    - [x] Recuperar senha
 - [x] Permitir que a Api seja consumida por outros endereços
   - [x] Instalar e configurar biblioteca CORS
- [x] **Versionar Api**
- [ ] **Adicionar testes**
- [ ] **Upload de ficheiros**
- [ ] **Notificações**
  - [x] Notificar o usuário por e-mail quando sua situação for comentada
     - [ ] Criar template de e-mail
  - [x] Configurar Queues (Filas)
  - [x] Notificar o usuário por database quando sua situação for comentada
- [x] **Permitir usuários publicar situações (Rest full)**
  - [x] Criar
  - [x] Listar
  - [x] Actualizar
  - [x] Ver
  - [x] Eliminar
  - [x] Validações
  - [x] Paginação
- [x] **Permitir usuários comentar situações**
  - [x] Criar
  - [x] Listar
  - [x] Actualizar
  - [x] Eliminar
  - [x] Validações
- [x] **Permitir usuário cadacastrar perfil**
  - [x] Criar
  - [x] Actualizar
  - [x] Validações
- [ ] **Recursos para constituição**
  - [ ] **Títulos**
    - [ ] Criar
    - [ ] Actualizar
    - [ ] Eliminar
    - [ ] Listar
    - [ ] Validações
  - [ ] **Capítulos**
    - [ ] Criar
    - [ ] Actualizar
    - [ ] Eliminar
    - [ ] Listar
    - [ ] Validações
  - [ ] **Secções**
    - [ ] Criar
    - [ ] Actualizar
    - [ ] Eliminar
    - [ ] Listar
    - [ ] Validações
  - [ ] **Artigos**
    - [ ] Criar
    - [ ] Actualizar
    - [ ] Eliminar
    - [ ] Listar
    - [ ] Validações
    - [ ] Paginação
